sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.7.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.7.deb && sudo service elasticsearch restart
  - sleep 10
  - pwd
  - curl -H 'Content-Type: application/x-ndjson' -XPOST '127.0.0.1:9200/_bulk?pretty' --data-binary @/home/travis/build/minibio/miniduke/src/test/resources/test_file/miniduke_test.json
