sudo: required

language: java

services:
  - docker

before_install:
- docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.12
- docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "transport.host=127.0.0.1" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:5.6.12
- curl -H 'Content-Type: application/x-ndjson' -XPOST '127.0.0.1:9200/_bulk?pretty' --data-binary @src/test/resources/test_file/miniduke_test.json

script:
- gradle build