sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.7.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.7.deb && sudo service elasticsearch restart
  - sleep 10
  - ./src/test/resources/test_file/index_data.sh